### ISSUE TITLE
Waarom staat dit publiek?

### ISSUE THREAD

**Issue by sanmai-NL** [TS-Yaloshi/ICSS-Tool-#6]

**Comment by TS-Yaloshi** [comment]
1. Zodat ik het aan anderen kan laten zien en/of discussies erover kan hebben.
2. Misschien uit jouw insteek meer relevant: op aanbeveling van een HAN docent.

**Comment by sanmai-NL** [comment]
Discussies kan je ook hebben door specifieke gebruikers toegang te geven.

**Comment by TS-Yaloshi** [comment]
Dan moet er eerst om toegang gevraagd worden. Geen ideale situatie voor een portfolio.
Overigens kan ik ook geen persoonlijke redenen bedenken waarom ik de repository niet op public zou willen hebben.

**Comment by DennisBreuker** [comment]
Wat betreft je opmerking "_op aanbeveling van een HAN docent_":

Ik heb niet gezegd: "zet je code maar openbaar". Ik heb gezegd dat het verstandig is om git te gebruiken, ook als je in je eentje werkt. Dat is dus git (en geen github), en alleen lokaal.


En wat betreft je opmerking "_Zodat ik het aan anderen kan laten zien en/of discussies erover kan hebben_":

Je kan ook met anderen discussiëren over je code door een Teams-sessie te openen en je scherm te delen. Dan deel je maar een klein deel (namelijk waarover je discussieert), en kan het alleen worden overgenomen door het over te typen, wat een grote drempel is. Dat komt meer overeen met hoe het fysiek zonder corona zou gaan.

Wanneer je code van een individuele opdracht waar je een cijfer voor krijgt digitaal deelt (in een repo), wordt het erg gemakkelijk voor anderen om dat over te nemen en werk je op die manier dus (ongewild) mee aan plagiaat. Dat is onwenselijk.

Als je graag een portfolio maakt (waar ik achter sta), zorg dan dat je de code voor individuele opdrachten pas openbaar maakt al de cijfers zijn gegeven, en doe dat ook in overleg met je docent. Misschien is er eerst nog een herkansing waarop moet worden gewacht, bijvoorbeeld.


Laten we verdere discussie maar per mail/teams doen.

**Comment by TS-Yaloshi** [comment]
Ik meende dat de opmerking over git óók in de context over een portfolio was. Gezien blijkt dat dat niet zo is, mijn excuses voor het gebruik daarvan in deze context.

Aan anderen laten zien en portfolio werd hier hetzelfde mee bedoeld.

Openbaarmaking voor de deadline was inderdaad onbedoeld, vandaar dat ik je ook erover gemaild heb. 
Mochten er nog andere richtlijnen/afspraken zijn omtrent github en schoolopdrachten, dan graag via mail/teams. Ook voor overleg over deze repo.

**Comment by sanmai-NL** [comment]
Ook na de deadline blijven uitwerkingen van standaardopdrachten vertrouwelijk. Er is ook een andere course, van mij, die deze opdracht heeft. Voor een portfolio kan je beter ander werk gebruiken. Net als dat je geen kennistoetsuitwerking publiek zou maken om te laten zien dat je veel goede antwoorden gaf.

Jouw e-mailadres ken ik trouwens niet. Jij en @DennisBreuker zullen het verder bespreken.
